#!/bin/sh
#==========================================================

# config path
make_path="$(pwd)"
openwrt_dir="openwrt"
imagebuilder_path="${make_path}/${openwrt_dir}"

# config repo
imagebuilder_repo="https://dl.openwrt.ai/releases/24.10/targets/x86/generic/kwrt-imagebuilder-x86-generic.Linux-x86_64.tar.zst"

# config package
unused_packages=""
driver_packages=""
default_luci=""
my_packages="${default_luci} ${driver_packages} ${unused_packages}"

error_msg() {
    echo -e "${ERROR} ${1}"
    exit 1
}

download_imagebuilder () {
    wget ${imagebuilder_repo} || error_msg
    tar -I zstd -xvf kwrt-imagebuilder-* && rm -f kwrt-imagebuilder-*.tar.zst
    mv -f kwrt-imagebuilder-* ${openwrt_dir}
}

build_firmware () {
    cd ${imagebuilder_path}
    sed -i 's/https//:file://www/wwwroot//g' repositories.conf
    make image PROFILE="generic" PACKAGES="${my_packages}" FILES="files" || error_msg
    echo "success..."
}

download_imagebuilder
build_firmware

exit 0
