#!/bin/sh
#==========================================================

# config path
make_path="$(pwd)"
openwrt_dir="openwrt"
imagebuilder_path="${make_path}/${openwrt_dir}"

# config repo
imagebuilder_repo="https://downloads.immortalwrt.org/snapshots/targets/x86/generic/immortalwrt-imagebuilder-x86-generic.Linux-x86_64.tar.xz"
# luci_app_passwall2="https://github.com/xiaorouji/openwrt-passwall2/releases/download/1.19-6/luci-app-passwall2_1.19-6_all.ipk"
# luci_i18n_passwall2_zh_cn="https://github.com/xiaorouji/openwrt-passwall2/releases/download/1.19-6/luci-i18n-passwall2-zh-cn_1.19-6_all.ipk"
# alist="https://github.com/sbwml/luci-app-alist/releases/download/v3.29.1/openwrt-21.02-i386_pentium4.tar.gz"

# config package
unused_packages="-luci-app-cpufreq"
driver_packages=""
default_luci="luci luci-i18n-base-zh-cn luci-i18n-firewall-zh-cn luci-i18n-opkg-zh-cn luci-compat luci-lib-base luci-lib-fs luci-lib-ipkg"
my_packages="${default_luci} luci-i18n-alist-zh-cn luci-i18n-aria2-zh-cn luci-i18n-samba4-zh-cn luci-i18n-vsftpd-zh-cn luci-i18n-diskman-zh-cn luci-i18n-argon-config-zh-cn ${driver_packages} ${unused_packages}"

error_msg() {
    echo -e "${ERROR} ${1}"
    exit 1
}

download_imagebuilder () {
    wget ${imagebuilder_repo} || error_msg
    tar -xJf immortalwrt-imagebuilder-* && rm -f immortalwrt-imagebuilder-*.tar.xz
    mv -f immortalwrt-imagebuilder-* ${openwrt_dir}
}

# custom_packages () {
#    wget -P ${imagebuilder_path}/packages/ ${luci_app_passwall2} || error_msg
#    wget -P ${imagebuilder_path}/packages/ ${luci_i18n_passwall2_zh_cn} || error_msg
#    wget ${alist} || error_msg
#    tar -zxvf openwrt-22.03-i386_pentium4.tar.gz -C ${imagebuilder_path}/packages/
# }

build_firmware () {
    cd ${imagebuilder_path}
    make image PROFILE="generic" PACKAGES="${my_packages}" FILES="files" || error_msg
    echo "success..."
}

download_imagebuilder
custom_packages
build_firmware

exit 0
