name: Immortalwrt_ImageBuilder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        run: |
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
          sudo -E apt-get -y update
          sudo -E apt-get -y install qemu-utils mkisofs
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean        

      - name: Run make-x86
        run: |
          sudo chmod +x make-x86
          sudo ./make-x86
          sudo timedatectl set-timezone Asia/Shanghai
          echo "BUILD_TAG=ImmortalWrt-Snapshots-x86_$(date +"%Y.%m.%d")" >> ${GITHUB_ENV}          
      
      - name: Upload OpenWrt Firmware to Release
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        with:
          tag: ${{ env.BUILD_TAG }}
          artifacts: "openwrt/bin/targets/x86/generic/*"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
