name: Immortalwrt-x86

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Run make-x86
        run: |
          sudo apt update
          sudo apt install qemu-utils mkisofs -y
          sudo chmod +x make-x86
          sudo ./make-x86
      
      - name: Upload OpenWrt Firmware to Release
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        with:
          tag: immortalwrt-snapshots-x86
          artifacts: "openwrt/bin/targets/x86/generic/*"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
